//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public System.DateTime SELL_DATE { get; set; }
        public System.DateTime DELIVERY_DATE { get; set; }
        public int PRODUCT_QUANTITY { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PRODUCTS_WAREHOUSE PRODUCTS_WAREHOUSE { get; set; }
    }
}
