//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS_WAREHOUSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS_WAREHOUSE()
        {
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string CATEGORY { get; set; }
        public decimal PRICE { get; set; }
        public string UNTI { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
    }
}
