//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALT()
        {
            this.AUTHORIZATIONs = new HashSet<AUTHORIZATION>();
        }
    
        public int ID { get; set; }
        public string VALUE { get; set; }
        public int CLIENT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHORIZATION> AUTHORIZATIONs { get; set; }
        public virtual CLIENT CLIENT { get; set; }
    }
}
